{{- if .Values.storefront.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storeName }}-storefront
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
    app.kubernetes.io/component: storefront
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: 8000
      targetPort: http
      name: http
      {{- if and (eq (.Values.service.type | default "ClusterIP") "NodePort") .Values.service.storefrontNodePort }}
      nodePort: {{ .Values.service.storefrontNodePort }}
      {{- end }}
  selector:
    {{- include "medusa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: storefront
{{- end }}
